sudo: required
dist: trusty
env:
  global:
    - CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN
addons:
  chrome: stable
language: node_js
node_js:
  - 11.10.0
before_install:
  - echo "$TRAVIS_BRANCH"
  - echo "$TRAVIS_PULL_REQUEST"
  - npm i -g npm
  - npm i -g codecov
  - npm i -g codacy-coverage
  - npm i -g live-server@1
  - npm i -g node-gyp@3
  - cd src/ngx-smart-loader
install:
  - npm install
script:
  - npm run test
  - npm run build
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
after_success:
  - codecov -t $CODECOV_TOKEN
  - cat coverage/lcov.info | codacy-coverage
  - rm -r node_modules
  - cd ../..
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then npm run ghpages; fi
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $PUSH_TOKEN
  on:
    branch: master
